[package]
name = "tsetlin_machine"
version = "0.1.0"
authors = ["Khaled Sharif <kldsrf@gmail.com>", "Erling Indstøy Langlo <erlinl18@uia.no>"]

[dependencies]
rand = "0.8.4"
csv = "1.0.0-beta.5"
ndarray = "0.15.3"
bitvec = "0.22.3"
